plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.wildriftresearch.oodleextractor'
    compileSdk 36

    defaultConfig {
        applicationId 'dev.wildriftresearch.oodleextractor'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
